TARGET : sconfig.exe sconfig.hlp
	echo Finished!

sconfig.hlp : sconfig.src
	helpgen sconfig.src

sconfig.exe : sconfig.obj s_apath.obj s_cfg.obj s_date.obj s_event.obj \
	s_fedit.obj s_file.obj s_flist.obj s_gen.obj s_gpath.obj s_main.obj \
	s_medit.obj s_menu.obj s_misc.obj s_modem.obj s_msel.obj s_msg.obj \
	s_npath.obj s_times.obj s_upath.obj s_users.obj s_util.obj
	wlink @makefile.lst

sconfig.obj : sconfig.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c sconfig.c > sconfig.err
	type sconfig.err

s_apath.obj : s_apath.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_apath.c > s_apath.err
	type s_apath.err

s_cfg.obj : s_cfg.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_cfg.c > s_cfg.err
	type s_cfg.err

s_date.obj : s_date.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_date.c > s_date.err
	type s_date.err

s_event.obj : s_event.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_event.c > s_event.err
	type s_event.err

s_fedit.obj : s_fedit.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_fedit.c > s_fedit.err
	type s_fedit.err

s_file.obj : s_file.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_file.c > s_file.err
	type s_file.err

s_flist.obj : s_flist.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_flist.c > s_flist.err
	type s_flist.err

s_gen.obj : s_gen.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_gen.c > s_gen.err
	type s_gen.err

s_gpath.obj : s_gpath.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_gpath.c > s_gpath.err
	type s_gpath.err

s_main.obj : s_main.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_main.c > s_main.err
	type s_main.err

s_medit.obj : s_medit.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_medit.c > s_medit.err
	type s_medit.err

s_menu.obj : s_menu.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_menu.c > s_menu.err
	type s_menu.err

s_misc.obj : s_misc.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_misc.c > s_misc.err
	type s_misc.err

s_modem.obj : s_modem.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_modem.c > s_modem.err
	type s_modem.err

s_msel.obj : s_msel.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_msel.c > s_msel.err
	type s_msel.err

s_msg.obj : s_msg.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_msg.c > s_msg.err
	type s_msg.err

s_npath.obj : s_npath.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_npath.c > s_npath.err
	type s_npath.err

s_times.obj : s_times.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_times.c > s_times.err
	type s_times.err

s_upath.obj : s_upath.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_upath.c > s_upath.err
	type s_upath.err

s_users.obj : s_users.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_users.c > s_users.err
	type s_users.err

s_util.obj : s_util.c sconfig.h
	wcl -ml -of+xt -s -zp1 -w4 -zt20 -c s_util.c > s_util.err
	type s_util.err

