# Makefile for Watcom C 9.0
#
# SPACK - Mail packing for Simplex


spack.exe : spack.obj s_analys.obj s_pack.obj
	wlink @makefile.lst

spack.obj : spack.c spack.h
	wcl -mc -ox -s -zp1 -w4 -c spack.c > spack.err
	type spack.err

s_analys.obj : s_analys.c spack.h
	wcl -mc -ox -s -zp1 -w4 -c s_analys.c > s_analys.err
	type s_analys.err

s_pack.obj : s_pack.c spack.h
	wcl -mc -ox -s -zp1 -w4 -c s_pack.c > s_pack.err
	type s_pack.err

